#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */
define('YII_DEBUG', true);
define('YII_ENV', 'dev');


require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';


$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
