#!/bin/bash

set -o errexit # Exit on error
YIICMD="php yii-test"

pushd ./src/server > /dev/null
echo "Setting up database ..."
$YIICMD migrate/fresh --interactive=0 --db=testdb --migrationNamespaces=app\\migrations\\schema  > /dev/null
$YIICMD migrate/up    --interactive=0 --db=testdb --migrationNamespaces=app\\migrations\\data    > /dev/null
$YIICMD migrate/up    --interactive=0 --db=testdb --migrationNamespaces=app\\tests\\migrations   > /dev/null

echo "Deleting log and output data files..."
[[ -f runtime/logs/app.log ]] && rm runtime/logs/app.log
[[ -f runtime/logs/error.log ]] && rm runtime/logs/error.log
rm tests/_output/*fail* &> /dev/null || true

echo "Running tests..."
php vendor/bin/codecept $@

echo "Cleanup database ..."
$YIICMD migrate/down all --interactive=0 --db=testdb  > /dev/null

popd > /dev/null

