#!/bin/bash

set -e error
# Compiles and starts the application from the source dir
# This is currently MacOS only and should probably be a node script.

# CLI params
TARGET=${1:-source}
APP=${2:-bibliograph}
HOST=${3:-localhost:9090}

# Constants
APP_PATH=client/bibliograph/compiled/$TARGET/$APP/index.html
COMPILE_PATH=$(pwd)/src/client/bibliograph

if ! [[ -d $COMPILE_PATH ]]; then
  echo "Cannot find client application - are you in the repo root?";
  exit 1;
fi

# start PHP Server
build/script/start-server $HOST

if [[ "$TARGET" != "server-only" ]]; then
    echo ">>> Compiling application..."
    pushd $COMPILE_PATH > /dev/null
    ( npx qx compile --target=source --watch --feedback=0 & ) | while read output; do
      echo "$output"
      # wait for "made" event message to resume script
      if [[ $output == *"Applications are made"* ]]; then break; fi;
    done

    echo ">>> Started continuous compilation process."
    popd > /dev/null
fi

if [[ "$TARGET" == "server-only" ]]; then
  exit 0
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  build/script/start-mysql
  echo ">>> Opening app in browser at http://$HOST/$APP_PATH"
  open -a "Google Chrome" http://$HOST/$APP_PATH
  # send Alt+Command+I to open Web inspector
  # osascript -e 'tell application "System Events" to keystroke "i" using {option down, command down}'
fi

# idle waiting for abort from user
read -r -d '' _ </dev/tty
