#!/usr/bin/env bash

# Checks the environment in which the tool scripts can run properly

[ "$(type -t mysql_root)" == "function" ] || source tool/lib/functions.sh

if ! type docker > /dev/null; then
  echo "ERROR: You need docker for the development environment"
  exit 1
fi

if ! [ -f "./package.json" ]; then
  >&2 echo 'ERROR: All tool scripts need to be executed from the bibliograph root directory'
  exit 1
fi
