#!/usr/bin/env bash
# Install compile-time dependencies

source tool/env/check
source ./tool/lib/functions.sh

if [[ "$GITHUB_WORKFLOW" == "" ]]; then
  # we're not on github
  tool/env/servers-stop
  docker system prune -f
  echo " >>> Downloading mariadb image"
  docker pull mariadb
fi

echo " >>> Downloading and starting PHPFarm docker container"
docker pull cboulanger/docker-phpfarm

tool/env/http-test
tool/env/http-server start

echo ">>> Installing composer ..."
EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
tool/dev/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" || exit 1
ACTUAL_SIGNATURE=$(tool/dev/php -r "echo hash_file('sha384', 'composer-setup.php');")

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    >&2 echo 'ERROR: Invalid installer signature'
    rm composer-setup.php
    exit 1
fi

tool/dev/php composer-setup.php --install-dir=src/lib #--quiet
RESULT=$?
rm composer-setup.php
if [ $RESULT -eq 1 ]; then
  >&2 echo "ERROR: Failed to setup composer ..."
  exit 1
fi

source tool/env/update
