#!/usr/bin/env bash
# Install compile-time dependencies

source tool/env/check
source ./tool/lib/functions.sh

tool/env/servers-stop
docker system prune -f

echo " >>> Downloading PHPFarm image"
docker pull cboulanger/docker-phpfarm

echo " >>> Downloading mariadb image"
docker pull mariadb

tool/env/http-server start

# fixes
docker exec -it http-server sh -c 'echo "FcgidIOTimeout 600" >>/etc/apache2/conf.d/phpfarm.conf'
docker exec -it http-server sh -c 'echo "FcgidConnectTimeout 20" >>/etc/apache2/conf.d/phpfarm.conf'
docker exec -it http-server sh -c 'echo "FcgidBusyTimeout 3600" >>/etc/apache2/conf.d/phpfarm.conf'

# additional packages
docker exec -it http-server apt-get update > /dev/null
docker exec -it http-server apt-get install git unzip mysql-client -y > /dev/null

echo ">>> Installing composer ..."
EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
tool/dev/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" || exit 1
ACTUAL_SIGNATURE=$(tool/dev/php -r "echo hash_file('sha384', 'composer-setup.php');")

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    >&2 echo 'ERROR: Invalid installer signature'
    rm composer-setup.php
    exit 1
fi

tool/dev/php composer-setup.php --install-dir=src/lib #--quiet
RESULT=$?
rm composer-setup.php
if [ $RESULT -eq 1 ]; then
  >&2 echo "ERROR: Failed to setup composer ..."
  exit 1
fi

source tool/env/update
