#!/usr/bin/env bash
# Install compile-time dependencies

[[ -z "$FUNCTIONS_LOADED" ]] && source tool/lib/functions.sh
source tool/env/check
source tool/env/envvars-load

if [[ "$GITHUB_WORKFLOW" == "" ]]; then
  source tool/env/services-install
  source tool/env/services-start
fi

echo ">>> Installing Qooxdoo..."

if command -v "pnpm" >/dev/null ; then
  pnpm add @qooxdoo/compiler
else
  npm install @qooxdoo/compiler
fi

log_info ">>> Installing composer ..."

COMPOSER_SETUP_SCRIPT=src/lib/composer-setup.php
EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
wget https://getcomposer.org/installer -O $COMPOSER_SETUP_SCRIPT
ACTUAL_SIGNATURE=$(tool/bin/php -r "echo hash_file('sha384', '$COMPOSER_SETUP_SCRIPT');")

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
    >&2 echo 'ERROR: Invalid installer signature'
    rm $COMPOSER_SETUP_SCRIPT
    exit 1
fi

tool/bin/php $COMPOSER_SETUP_SCRIPT --install-dir=src/lib #--quiet
RESULT=$?
rm $COMPOSER_SETUP_SCRIPT
if [ $RESULT -eq 1 ]; then
  exit_with_error "ERROR: Failed to setup composer ..."
fi

log_info ">>> Installing Qooxdoo packages..."
npx qx package update --quiet
npx qx package install

log_info ">>> Installing Composer packages..."
tool/env/composer-install
