#!/usr/bin/env bash

[[ -z "$FUNCTIONS_LOADED" ]] && source tool/lib/functions.sh
source tool/env/envvars-load

echo ">>> Testing MySQL service"
docker exec -it mysql_server cat /etc/os-release | grep VERSION=

if [[ "$GITHUB_WORKFLOW" != "" ]]; then
  echo -n ">>> Checking connection from the host to the MySQL service container using $DB_HOST:$DB_PORT..."
  COUNTER=0
  TIMEOUT=20
  while ! mysqladmin ping -h"$DB_HOST_GITHUB" -P"$DB_PORT_GITHUB" --silent; do
    sleep 1
    let "COUNTER+=1"
    if [[ $COUNTER == $TIMEOUT ]]; then
      echo "Timeout."
      exit 1
    fi
  done
  echo "${CHECKMARK}"
  mysql -uroot -p$DB_ROOT_PASSWORD --version
else
  echo -n ">>> Checking mysql root access via the MySQL service container ... "
  output=$(tool/dev/mysql-client -uroot -p$DB_ROOT_PASSWORD --version)
  if [ $? -ne 0 ]; then echo "$CROSSMARK"; log_error $output; exit 1; fi
  echo "${CHECKMARK}"
  echo "$output"
fi

echo -n ">>> Checking mysql root access connection from PHP in the HTTP-Server container using $DB_HOST:$DB_PORT ... "
tool/dev/php -r "if(!@mysqli_connect('$DB_HOST', 'root', '$DB_ROOT_PASSWORD', '', $DB_PORT)){echo '$CROSSMARK' . PHP_EOL .'${COLOR_RED}Error: '.mysqli_connect_error().PHP_EOL.'${STYLE_RESET}';exit(1);}"
echo "${CHECKMARK}"
