#!/usr/bin/env bash

if [[ "$GITHUB_WORKFLOW" != "" ]]; then
  echo ">>> No need to install service containers on GitHub"
else
  tool/env/services-stop
  docker system prune -f
  echo " >>> Downloading mariadb image"
  docker pull mariadb
  echo " >>> Downloading and starting PHPFarm docker container"
  docker pull cboulanger/docker-phpfarm
fi
