#!/usr/bin/env bash
# Update dependencies

set -e
source tool/env/check
source tool/env/install-libs

echo ">>> Installing/updating Qooxdoo..."

if command -v "pnpm" >/dev/null ; then
  pnpm add @qooxdoo/compiler
else
  npm install @qooxdoo/compiler
fi

echo ">>> Installing/updating Qooxdoo packages..."
npx qx package update --quiet
npx qx package upgrade

echo ">>> Updating Composer packages..."
tool/dev/composer update
