#!/usr/bin/env bash

# until the docker image is updated
docker exec -it http-server git version 2&> /dev/null
if [ $? -ne 0 ]; then
 echo "Installing git in container, please wait... "
 docker exec -it http-server apt update
 docker exec -it http-server apt install git -y
fi

# call local composer with the right working directory
tool/dev/php src/lib/composer.phar --working-dir=src/server "$@"
