#!/usr/bin/env bash

# check and export environment variables for use in scripts
envvars="PHP_VERSION DB_TYPE DB_HOST DB_PORT DB_USER DB_PASSWORD DB_DATABASE"
for envvar in $envvars; do
  #echo "$envvar is ${!envvar}"
  if [ "${!envvar}" == "" ]; then
    log_error "You need to set the '$envvar' environment variable."
    exit 1
  fi
  export $envvar
done
