#!/usr/bin/env bash
# Install compile-time dependencies

source tool/dev/check-env
source ./tool/lib/functions.sh

echo " >>> Downloading PHPFarm image"
docker pull cboulanger/docker-phpfarm

echo " >>> Downloading mariadb image"
docker pull mariadb

echo ">>> Installing git in http-server container"
tool/dev/http-server start

if ! [ -f src/lib/composer.phar ] ; then
  echo " >>> Installing composer ..."
  EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
  tool/dev/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

  if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
  then
      >&2 echo 'ERROR: Invalid installer signature'
      rm src/server/composer-setup.php
      exit 1
  fi

  tool/dev/php composer-setup.php --install-dir=src/lib #--quiet
  RESULT=$?
  rm src/server/composer-setup.php
  if [ $RESULT -eq 1 ]; then
    >&2 echo "ERROR: Failed to setup composer ..."
    exit 1
  fi
fi

# Install needed GitHub repos
echo " >>> Installing github repositories..."

declare -a arr=(
  "cboulanger/yii2-jsonrpc"
  "cboulanger/raptor-client"
  "cboulanger/dsn"
  "cboulanger/worldcat-linkeddata-php"
  "serratus/quaggaJS"
)
for repo in "${arr[@]}"
do
  dir=./src/lib/$(basename $repo)
  if [ -d "$dir" ]; then
    echo "Updating $repo..."
    pushd $dir > /dev/null || exit 1
    git pull
    [[ -f package.json ]] && npm install
    popd > /dev/null
  else
    echo "Checking out $repo..."
    uri="https://github.com/$repo.git"
    git clone $uri --depth 1 $dir
    pushd $dir > /dev/null || exit 1
    [[ -f package.json ]] && npm install --only=prod && npm audit fix
    popd > /dev/null
  fi
done
