#!/usr/bin/env bash

source tool/env/check

TARGET=${1:-app}
LOGFILE=log/app/$TARGET.log

case $1 in
view)
  CMD="tail -F -n 1000 $LOGFILE"
  tool/dev/terminal "$CMD"
  ;;
clear)
  [[ -f $LOGFILE ]] && rm $LOGFILE
  touch $LOGFILE
  ;;
*)
  echo "Syntax: tool/dev/log (view|clear) (app|error)?"
esac
