#!/usr/bin/env bash
LOGFILE="$(pwd)/src/server/runtime/logs/${1:-app}.log"
#if hash ccze ; then
#  CMD="tail -F -n 20 $LOGFILE | ccze"
#else
  CMD="tail -F -n 1000 $LOGFILE"
#fi
build/script/run-in-new-terminal "$CMD"



