#!/usr/bin/env bash

if [[ "$GITHUB_WORKFLOW" != "" ]]; then
  # really needed? check if the other option just works on github, too
  mysql -h$DB_HOST_GITHUB -P$DB_PORT_GITHUB "$@"
else
  docker exec mysql_server mysql "$@"
fi
