#!/usr/bin/env bash

# read environment variables
./tool/dev/check-env && source ./.env

# run php in docker image
docker run --rm -t -i -v $PWD:/var/www:rw cboulanger/docker-phpfarm:latest php-$PHP_VERSION "$@"
