#!/bin/bash

# Compiles and starts the bibliograph app in the browser

set -o errexit
source test/.env
source tool/env/check
source tool/env/envvars-export
if [ "$1" == "clean" ]; then
  source tool/test/setup/create-mysql-user
  source tool/test/setup/reset-data
fi
source tool/test/setup/check-mysql
export APP_URL
tool/dev/start-app bibliograph
