#!/usr/bin/env bash

# export .env variables to this shell
export $(egrep -v '^#' .env | xargs)

if [[ "$(tool/dev/mysql-server status)" == *"not running"* ]]; then
  tool/dev/mysql-server start || exit 1
fi

if [[ "$(tool/dev/http-server status)" == *"not running"* ]]; then
  tool/dev/http-server start
fi
