#!/bin/bash

# Compiles and starts the given app in the browser in development mode
set -o errexit
source tool/env/envvars-load
source tool/env/envvars-export

APP=${1:-bibliograph}
CONFIG_FILE=${2:-compile.json}
APP_PATH=compiled/source/$APP
TARGET=${3:-source}

echo ">>> Compiling application '$APP', using config file '$CONFIG_FILE' and '$TARGET' target ..."
(npx qx compile --target=$TARGET --watch --feedback=0 -c $CONFIG_FILE & ) | while read output; do
  echo "$output"
  # wait for "made" event message to resume script
  if [[ $output == *"Applications are made"* ]]; then break; fi;
done

sleep 5

echo ">>> Started continuous compilation process."

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo ">>> Opening app in browser at $BIB_SERVER_URL/$APP_PATH"
  open -a "Google Chrome" "$BIB_SERVER_URL/$APP_PATH"
  # send Alt+Command+I to open Web inspector
  osascript -e 'tell application "System Events" to keystroke "i" using {option down, command down}'
fi

# idle waiting for abort from user
read -r -d '' _ </dev/tty
