#!/usr/bin/env bash

./tool/dev/check-env && source ./.env

tool/dev/mysql-server start
tool/dev/http-server start

tool/dev/mysql-client -uroot -p$DB_ROOT_PASSWORD --version || (echo "Something wrong witht the mysql server setup" || exit 1)

TEST_CONNECT=<< EOF
$link = mysqli_connect("host.docker.internal", "root", "bibliograph");

if (!$link) {
    echo "Error: Unable to connect to MySQL." . PHP_EOL;
    echo "Debugging errno: " . mysqli_connect_errno() . PHP_EOL;
    echo "Debugging error: " . mysqli_connect_error() . PHP_EOL;
    exit;
}
EOF
tool/dev/php -r
