#!/usr/bin/env bash
# Update dependencies

./tool/dev/check-env && source ./.env

echo " >>> Updating packages..."
pushd src/client/bibliograph >/dev/null
qx pkg upgrade --prereleases --releases-only
popd >/dev/null

echo " >>> Updating composer packages..."
pushd src/server >/dev/null
composer update
pushd vendor >/dev/null
[[ -d bower ]] || ln -s bower-asset/ bower
popd >/dev/null
popd >/dev/null

echo " >>> Updating cloned GitHub repos..."
pushd src/vcslib >/dev/null
bash install.sh
popd >/dev/null
