#!/bin/bash

source tool/test/setup/drop-database
source tool/test/setup/create-database

echo ">>> Deleting log and output data files..."
rm log/app/*.log* || true
[[ -f log/codeception.migration.log ]] && rm log/codeception.migration.log
rm test/codeception/_output/*fail* || true
