#!/bin/bash

source tool/test/setup/drop-database
source tool/test/setup/create-database

echo ">>> Deleting log and output data files..."
[[ -f log/app/app.log ]] && rm log/app/app.log
[[ -f log/app/error.log ]] && rm log/app/error.log
[[ -f log/codeception.migration.log ]] && rm log/codeception.migration.log
rm test/codeception/_output/*fail* || true
