#!/bin/bash

# This sets up the database for the model data
source test/.env
[ "$(type -t mysql_root)" == "function" ] || source tool/lib/functions.sh

MIGRATE_ARGS="--interactive=0"
MIGRATE_LOGFILE=log/codeception.migration.log
[ -f $MIGRATE_LOGFILE ] && rm $MIGRATE_LOGFILE

source tool/dev/drop-database
source tool/dev/create-database

echo ">>> Deleting log and output data files..."
[[ -f logs/app/app.log ]] && rm logs/app/app.log
[[ -f logs/app/error.log ]] && rm logs/app/error.log
rm test/codeception/_output/*fail* || true

log_info -n ">>> Creating model data (Logfile at ${MIGRATE_LOGFILE}) ."
yii_test migrate/up --migrationNamespaces=app\\migrations\\schema $MIGRATE_ARGS &> $MIGRATE_LOGFILE
log_info -n "."
yii_test migrate/up --migrationNamespaces=app\\migrations\\data $MIGRATE_ARGS &> $MIGRATE_LOGFILE
log_info -n "."
yii_test migrate/up --migrationNamespaces=tests\\migrations $MIGRATE_ARGS &> $MIGRATE_LOGFILE
log_info " ${CHECKMARK}"
