/**
    Generated by QxTransformer v.0.4.
    Author Christian Boulanger
**/

/*------------------------------------------------------------------------------

------------------------------------------------------------------------------*/
qx.Class.define("bibliograph.ui.item.DuplicatesViewUi",
{
  extend : bibliograph.ui.item.DuplicatesView,
  construct : function()
  {
    this.base(arguments);
    this.__qxtCreateUI();
  },
  members : {
    __qxtCreateUI : function()
    {
      var qxVbox1 = new qx.ui.layout.VBox(5, null, null);
      var qxComposite1 = this;
      this.setLayout(qxVbox1)
      qxComposite1.setPadding(5);
      qxVbox1.setSpacing(5);
      var qxLabel1 = new qx.ui.basic.Label(this.tr('This table shows potential duplicates of the current record.'));
      qxLabel1.setValue(this.tr('This table shows potential duplicates of the current record.'));
      qxComposite1.add(qxLabel1);
      var duplicatesTable = new qx.ui.table.Table(null, {
        tableColumnModel : function(obj) {
          return new qx.ui.table.columnmodel.Resize(obj);
        }
      });
      this.duplicatesTable = duplicatesTable;
      duplicatesTable.setShowCellFocusIndicator(false);
      duplicatesTable.setStatusBarVisible(false);
      duplicatesTable.getSelectionModel().setSelectionMode(qx.ui.table.selection.Model.SINGLE_SELECTION);
      duplicatesTable.setKeepFirstVisibleRowComplete(true);
      qxComposite1.add(duplicatesTable, {
        flex : 1
      });

      // ------
      var qxTableModel1 = new qx.ui.table.model.Simple();
      qxTableModel1.setColumns(["RID", this.tr('Type'), this.tr('Author'), this.tr('Date'), this.tr('Title'), "%"], ["refId", "type", "author", "date", "title", "score"]);

      // -------
      duplicatesTable.setTableModel(qxTableModel1);
      duplicatesTable.getTableColumnModel().setColumnVisible(0, false);
      duplicatesTable.getTableColumnModel().setColumnWidth(0, 50);
      duplicatesTable.getTableColumnModel().getBehavior().setWidth(0, 50);
      duplicatesTable.getTableColumnModel().setColumnWidth(1, 150);
      duplicatesTable.getTableColumnModel().getBehavior().setWidth(1, 150);
      duplicatesTable.getTableColumnModel().setColumnWidth(3, 50);
      duplicatesTable.getTableColumnModel().getBehavior().setWidth(3, 50);
      duplicatesTable.getTableColumnModel().setColumnWidth(5, 30);
      duplicatesTable.getTableColumnModel().getBehavior().setWidth(5, 30);
      this.getApplication().addListener("changeModelId", this.reloadData, this);
      duplicatesTable.addListener("appear", this._on_appear, this);
      var qxHbox1 = new qx.ui.layout.HBox(5, null, null);
      var qxComposite2 = new qx.ui.container.Composite();
      qxComposite2.setLayout(qxHbox1)
      qxComposite2.setEnabled(false);
      qxComposite1.add(qxComposite2);
      qxHbox1.setSpacing(5);
      var qxButton1 = new qx.ui.form.Button(this.tr('Delete Duplicate'), null, null);
      qxButton1.setEnabled(false);
      qxButton1.setLabel(this.tr('Delete Duplicate'));
      qxComposite2.add(qxButton1);
      qx.core.Init.getApplication().getAccessManager().getPermissionManager().create("reference.remove").bind("state", qxButton1, "enabled", {

      });
      qxButton1.addListener("execute", this.deleteDuplicate, this);
    }
  }
});
