/*******************************************************************************
 *
 * Bibliograph: Online Collaborative Reference Management
 *
 * Copyright: 2007-2015 Christian Boulanger
 *
 * License: LGPL: http://www.gnu.org/licenses/lgpl.html EPL:
 * http://www.eclipse.org/org/documents/epl-v10.php See the LICENSE file in the
 * project's top-level directory for details.
 *
 * Authors: Christian Boulanger (cboulanger)
 *
 ******************************************************************************/

/*global qx qcl bibliograph*/

/**
 * A WYSIWYG editor view. Currently not functional and not used.
 */
qx.Class.define("bibliograph.ui.item.HtmlEditorUi",
{
  extend : bibliograph.ui.item.HtmlEditor,
  construct : function()
  {
    this.base(arguments);
    this.__qxtCreateUI();
  },
  members : {
    __qxtCreateUI : function() {
      //connecting autogenerated id with 'this'
      var qxWidget1 = this;
    }
  }
});
