/**
    Generated by QxTransformer v.0.4.
    Author Christian Boulanger
**/

/*------------------------------------------------------------------------------

------------------------------------------------------------------------------*/
qx.Class.define("bibliograph.ui.item.HtmlEditorUi",
{
  extend : bibliograph.ui.item.HtmlEditor,
  construct : function()
  {
    this.base(arguments);
    this.__qxtCreateUI();
  },
  members : {
    __qxtCreateUI : function() {
      //connecting autogenerated id with 'this'
      var qxWidget1 = this;
    }
  }
});
