#!/usr/bin/env bash
BACKEND_PATH=$( cd "$(dirname "$0")/../../src/server" ; pwd -P )
echo "Starting PHP Servers 7.0-7.4, serving from $BACKEND_PATH ..."
docker run \
    --rm -t -i \
    -e APACHE_UID=$UID \
    -v $BACKEND_PATH:/var/www:rw \
    -p 8070:8070 -p 8071:8071 -p 8072:8072 -p 8073:8073 -p 8074:8074 \
   cboulanger/docker-phpfarm

