/**
 Generated by QxTransformer v.0.4.
 Author Christian Boulanger
 **/

/*------------------------------------------------------------------------------

 ------------------------------------------------------------------------------*/
qx.Class.define("bibliograph.Application",
{
  extend : bibliograph.Main,
  members :
  {
    main : function()
    {
      this.base(arguments);
      var ui_winDatasourceListWindow1 = new bibliograph.ui.window.DatasourceListWindow();
      ui_winDatasourceListWindow1.setWidgetId("datasourceWindow");
      ui_winDatasourceListWindow1.setVisibility("excluded");
      this.getRoot().add(ui_winDatasourceListWindow1);
      var ui_winAccessControlTool1 = new bibliograph.ui.window.AccessControlTool();
      ui_winAccessControlTool1.setWidgetId("accessControlTool");
      ui_winAccessControlTool1.setVisibility("excluded");
      this.getRoot().add(ui_winAccessControlTool1);
      var ui_winFolderTreeWindow1 = new bibliograph.ui.window.FolderTreeWindowUi();
      ui_winFolderTreeWindow1.setWidgetId("folderTreeWindow");
      ui_winFolderTreeWindow1.setVisibility("excluded");
      this.getRoot().add(ui_winFolderTreeWindow1);
      var ui_winPreferencesWindow1 = new bibliograph.ui.window.PreferencesWindow();
      ui_winPreferencesWindow1.setWidgetId("preferencesWindow");
      ui_winPreferencesWindow1.setVisibility("excluded");
      this.getRoot().add(ui_winPreferencesWindow1);
      var ui_winImportWindow1 = new bibliograph.ui.window.ImportWindowUi();
      ui_winImportWindow1.setWidgetId("importWindow");
      ui_winImportWindow1.setVisibility("excluded");
      this.getRoot().add(ui_winImportWindow1);
      var ui_winAboutWindow1 = new bibliograph.ui.window.AboutWindow();
      ui_winAboutWindow1.setWidgetId("aboutWindow");
      ui_winAboutWindow1.setVisibility("excluded");
      this.getRoot().add(ui_winAboutWindow1);
      var ui_winSearchHelpWindow1 = new bibliograph.ui.window.SearchHelpWindow();
      ui_winSearchHelpWindow1.setWidgetId("searchHelpWindow");
      ui_winSearchHelpWindow1.setVisibility("excluded");
      this.getRoot().add(ui_winSearchHelpWindow1);
      var qxVbox1 = new qx.ui.layout.VBox(null, null, null);
      var qxComposite1 = new qx.ui.container.Composite();
      qxComposite1.setLayout(qxVbox1)
      this.getRoot().add(qxComposite1, {
        edge : 0
      });
      var qclLoginDialog1 = new qcl.ui.dialog.Login();
      qclLoginDialog1.setCallback(this.checkLogin);
      qclLoginDialog1.setWidgetId("loginDialog");
      qclLoginDialog1.setAllowCancel(true);
      qx.core.Init.getApplication().getConfigManager().addListener("ready", function() {
        qx.core.Init.getApplication().getConfigManager().bindKey("application.title", qclLoginDialog1, "text", false);
      });
      qx.core.Init.getApplication().getConfigManager().addListener("ready", function() {
        qx.core.Init.getApplication().getConfigManager().bindKey("application.logo", qclLoginDialog1, "image", false);
      });
      var ui_mainToolbar1 = new bibliograph.ui.main.Toolbar();
      qxComposite1.add(ui_mainToolbar1);
      var qxHsplit1 = new qx.ui.splitpane.Pane("horizontal");
      qxHsplit1.setOrientation("horizontal");
      qxComposite1.add(qxHsplit1, {
        flex : 1
      });
      var qxVbox2 = new qx.ui.layout.VBox(null, null, null);
      var qxComposite2 = new qx.ui.container.Composite();
      qxComposite2.setLayout(qxVbox2)
      qxHsplit1.add(qxComposite2, 1);
      var accordeon = new qx.ui.form.RadioGroup();
      accordeon.setAllowEmptySelection(true);
      var ui_mainFolderTreePanel1 = new bibliograph.ui.main.FolderTreePanel();
      qxComposite2.add(ui_mainFolderTreePanel1, {
        flex : 1
      });
      var qxVsplit1 = new qx.ui.splitpane.Pane("vertical");
      qxVsplit1.setOrientation("vertical");
      qxVsplit1.setDecorator(null);
      qxHsplit1.add(qxVsplit1, 3);
      var ui_mainReferenceListView1 = new bibliograph.ui.main.ReferenceListView();
      qxVsplit1.add(ui_mainReferenceListView1);
      var ui_mainItemView1 = new bibliograph.ui.main.ItemViewUi();
      ui_mainItemView1.setWidgetId("itemView");
      qxVsplit1.add(ui_mainItemView1);
      ui_mainItemView1.bind("view", this.getApplication(), "itemView", {});
      this.getApplication().bind("itemView", ui_mainItemView1, "view", {});
    }
  }
});
