<?php

return [
  [

    'id' => 1,
    'namedId' => 'database1',
    'created' => '2017-12-20 13:56:48',
    'modified' => '2017-12-20 14:56:48',
    'title' => 'Database 1',
    'description' => null,
    'schema' => 'bibliograph.schema.bibliograph2',
    'type' => 'mysql',
    'host' => 'localhost',
    'port' => 3306,
    'database' => 'tests',
    'username' => 'root',
    'password' => null,
    'encoding' => 'utf-8',
    'prefix' => 'database1_',
    'resourcepath' => null,
    'active' => 1,
    'readonly' => 0,
    'hidden' => 0,
  ],
  [
    'id' => 2,
    'namedId' => 'database2',
    'created' => '2017-12-20 13:56:48',
    'modified' => '2017-12-20 14:56:48',
    'title' => 'Database 2',
    'description' => null,
    'schema' => 'bibliograph.schema.bibliograph2',
    'type' => 'mysql',
    'host' => 'localhost',
    'port' => 3306,
    'database' => 'tests',
    'username' => 'root',
    'password' => null,
    'encoding' => 'utf-8',
    'prefix' => 'database2_',
    'resourcepath' => null,
    'active' => 1,
    'readonly' => 0,
    'hidden' => 0,
  ],
  [
    'id' => 3,
    'namedId' => 'setup',
    'created' => '2017-12-20 13:56:48',
    'modified' => '2017-12-20 14:56:48',
    'title' => null,
    'description' => null,
    'schema' => 'none',
    'type' => 'dummy',
    'host' => null,
    'port' => null,
    'database' => null,
    'username' => null,
    'password' => null,
    'encoding' => 'utf-8',
    'prefix' => null,
    'resourcepath' => null,
    'active' => 0,
    'readonly' => 0,
    'hidden' => 1,
  ],
  [
    'id' => 4,
    'namedId' => 'bibliograph_import',
    'created' => '2017-12-20 13:56:48',
    'modified' => '2017-12-20 14:56:48',
    'title' => null,
    'description' => null,
    'schema' => 'bibliograph.schema.bibliograph2',
    'type' => 'mysql',
    'host' => 'localhost',
    'port' => 3306,
    'database' => 'tests',
    'username' => 'root',
    'password' => null,
    'encoding' => 'utf-8',
    'prefix' => null,
    'resourcepath' => null,
    'active' => 1,
    'readonly' => 0,
    'hidden' => 1,
  ],
  [
    'id' => 5,
    'namedId' => 'bibliograph_export',
    'created' => '2017-12-20 13:56:48',
    'modified' => '2017-12-20 14:56:48',
    'title' => null,
    'description' => null,
    'schema' => 'qcl.schema.filesystem.local',
    'type' => 'file',
    'host' => null,
    'port' => null,
    'database' => null,
    'username' => null,
    'password' => null,
    'encoding' => 'utf-8',
    'prefix' => null,
    'resourcepath' => '/tmp',
    'active' => 1,
    'readonly' => 0,
    'hidden' => 1,
  ],
  [
    'id' => 7,
    'namedId' => 'z3950_BVB01MCZ',
    'created' => '2017-12-20 14:00:17',
    'modified' => '2017-12-20 15:00:17',
    'title' => 'Bibliotheksverbund Bayern (BVB)/B3Kat',
    'description' => null,
    'schema' => 'bibliograph.schema.z3950',
    'type' => 'mysql',
    'host' => 'localhost',
    'port' => 3306,
    'database' => 'tests',
    'username' => 'root',
    'password' => null,
    'encoding' => 'utf-8',
    'prefix' => 'z3950_BVB01MCZ_',
    'resourcepath' => '/Users/cboulanger/Code/bibliograph/bibliograph/plugins/z3950/services/class/z3950/servers/193.174.96.24-31310-BVBSR011.xml',
    'active' => 1,
    'readonly' => 0,
    'hidden' => 1,
  ],
  [
    'id' => 14,
    'namedId' => 'database3',
    'created' => '2017-12-21 11:40:26',
    'modified' => '2017-12-21 12:40:36',
    'title' => 'Sarah\'s Database',
    'description' => null,
    'schema' => 'bibliograph.schema.bibliograph2',
    'type' => 'mysql',
    'host' => 'localhost',
    'port' => 3306,
    'database' => 'bibliograph',
    'username' => null,
    'password' => null,
    'encoding' => 'utf-8',
    'prefix' => 'database3_',
    'resourcepath' => null,
    'active' => 1,
    'readonly' => 0,
    'hidden' => 0,
  ],
];