<?php

return [
    [
        'id' => 1,
        'created' => '2017-12-17 22:46:24',
        'modified' => '2017-12-28 16:38:09',
        'parentId' => 0,
        'position' => 0,
        'label' => 'Hauptordner',
        'type' => null,
        'description' => null,
        'searchable' => null,
        'searchfolder' => null,
        'query' => null,
        'public' => 1,
        'opened' => null,
        'locked' => null,
        'path' => null,
        'owner' => null,
        'hidden' => 0,
        'createdBy' => null,
        'markedDeleted' => 0,
        'childCount' => 2,
        'referenceCount' => 22,
    ],
    [
        'id' => 2,
        'created' => '2017-12-17 22:46:24',
        'modified' => '2017-12-17 22:47:06',
        'parentId' => 0,
        'position' => 1,
        'label' => 'Mülleimer',
        'type' => 'trash',
        'description' => null,
        'searchable' => null,
        'searchfolder' => null,
        'query' => null,
        'public' => null,
        'opened' => null,
        'locked' => null,
        'path' => null,
        'owner' => null,
        'hidden' => 0,
        'createdBy' => null,
        'markedDeleted' => 0,
        'childCount' => 0,
        'referenceCount' => 0,
    ],
    [
        'id' => 3,
        'created' => '2017-12-28 16:37:58',
        'modified' => '2017-12-28 16:40:37',
        'parentId' => 1,
        'position' => 0,
        'label' => 'Reference Management Software',
        'type' => null,
        'description' => null,
        'searchable' => null,
        'searchfolder' => 1,
        'query' => null,
        'public' => 1,
        'opened' => 1,
        'locked' => null,
        'path' => null,
        'owner' => null,
        'hidden' => 0,
        'createdBy' => 'admin',
        'markedDeleted' => 0,
        'childCount' => 1,
        'referenceCount' => 7,
    ],
    [
        'id' => 4,
        'created' => '2017-12-28 16:38:08',
        'modified' => '2017-12-28 16:38:48',
        'parentId' => 1,
        'position' => 1,
        'label' => 'Zotero',
        'type' => null,
        'description' => null,
        'searchable' => null,
        'searchfolder' => 1,
        'query' => 'title contains zotero',
        'public' => 1,
        'opened' => 1,
        'locked' => null,
        'path' => null,
        'owner' => null,
        'hidden' => 0,
        'createdBy' => 'admin',
        'markedDeleted' => 0,
        'childCount' => 0,
        'referenceCount' => 0,
    ],
    [
      'id' => 5,
      'created' => '2017-12-28 16:38:08',
      'modified' => '2017-12-28 16:38:48',
      'parentId' => 3,
      'position' => 0,
      'label' => 'Foo',
      'type' => null,
      'description' => null,
      'searchable' => null,
      'searchfolder' => 1,
      'query' => '',
      'public' => 1,
      'opened' => 1,
      'locked' => null,
      'path' => null,
      'owner' => null,
      'hidden' => 0,
      'createdBy' => 'admin',
      'markedDeleted' => 0,
      'childCount' => 0,
      'referenceCount' => 0,
  ],    
];