#!/usr/bin/env bash
HOST=127.0.0.1
PORT=7080
docker run -d -p $HOST:$PORT:80 cboulanger/bibliograph:$(git describe --tags)
if [[ "$OSTYPE" == "darwin"* ]]; then
  open -a "Google Chrome" http://$HOST:$PORT
  # send Alt+Command+I to open Web inspector
  osascript -e 'tell application "System Events" to keystroke "i" using {option down, command down}'
fi
