#!/bin/bash

source tool/env/envvars-load
source tool/env/check

CODECEPT_ARGS="--fail-fast"
set -o errexit
source tool/lib/functions.sh

tool/env/services-start
tool/env/services-test

declare -a default=(
  unit
  functional
  "api --env empty-database"
)
declare -a suites=("${@:-${default[@]}}")

log_heading "Running codeception suites '${suites[*]}' "

source tool/env/envvars-export
source tool/test/setup/create-mysql-user
source tool/test/setup/check-mysql

export APP_URL=http://localhost:$PORT/compiled/$BUILD_TARGET/$APP_NAME

for suite in "${suites[@]}"
do
    source tool/test/setup/reset-data
    if [[ "$suite" != *"--env empty-database"* ]]; then
      source tool/test/setup/create-model-data
    fi
    log_info ">>> Running test suite: $suite ..."
    codecept $CODECEPT_ARGS run $suite || exit $?
done

log_info "Tests finished."
exit 0
