#!/bin/bash

source tool/env/check
source tool/env/envvars-load

CODECEPT_ARGS="--fail-fast --no-ansi"
LOGFILE=log/codeception.log

set -o errexit
source tool/lib/functions.sh

tool/env/services-start
tool/env/services-test

declare -a default=(
  unit
  functional
  "api --env empty-database"
)
declare -a suites=("${@:-${default[@]}}")

# shellcheck disable=SC2206
php_versions=(${PHP_TEST_VERSIONS:-$PHP_VERSION})

# mysql setup
source tool/env/envvars-export
source tool/test/setup/create-mysql-user
source tool/test/setup/check-mysql

for php_version in "${php_versions[@]}"
do
  rm -f $LOGFILE
  log_heading "Running tests for PHP version $php_version (see logfile log/codeception.log for details)"
  # load default values
  source tool/env/envvars-load
  # override values in .env via .env.dev
  PHP_VERSION=$php_version
  PHP_PORT=8$(printf %03d ${PHP_VERSION/\./})
  APP_URL=http://localhost:$PHP_PORT/compiled/$BUILD_TARGET/$APP_NAME
  SERVER_URL=http://host.docker.internal:$PHP_PORT/test/codeception/web
  cat << EOF > test/.env.dev
PHP_VERSION=$PHP_VERSION
PHP_PORT=$PHP_PORT
APP_URL=$APP_URL
SERVER_URL=$SERVER_URL
EOF
  source tool/env/envvars-export
  # Install composer dependencies if necessary
  if ! [ -f "src/lib/composer-$php_version/vendor/autoload.php" ]; then
    log_info "Installing composer dependencies for PHP $php_version..."
    tool/bin/composer install
  fi
  # Run test suites
  for suite in "${suites[@]}"
  do
      source tool/test/setup/reset-data
      if [[ "$suite" != *"--env empty-database"* ]]; then
        source tool/test/setup/create-model-data
      fi
      log_info ">>> Running test suite: $suite (PHP $PHP_VERSION)..."
      EXIT_CODE=0
      codecept $CODECEPT_ARGS run $suite > $LOGFILE || EXIT_CODE=$?
      if [[ $EXIT_CODE != 0 ]] ; then
        cat $LOGFILE
        exit 1
      fi
  done
  rm test/.env.dev
done

log_info "Tests finished."
exit 0
