#!/bin/bash

# Usage
# tool/test/playwright [keep] [URL] [browser-type]

[ -d node_modules/playwright ] || test/playwright/install

# Compiles and starts the playwright tests
set -o errexit
source tool/env/envvars-load
source tool/env/check
source tool/lib/functions.sh
source tool/env/envvars-export

if [[ "$1" == "keep" ]]; then
  shift
else
  source tool/test/setup/create-mysql-user
  source tool/test/setup/check-mysql
  source tool/test/setup/reset-data
fi

npx qx compile --target=build
export APP_URL=${1:-http://localhost:8073/compiled/build/bibliograph/}
export BROWSER_TYPE=${2:-"chromium"}

tape test/playwright/test-*.js
