#!/bin/bash

# Usage
# tool/test/playwright [keep] [URL] [browser-type]

# Compiles and starts the playwright tests
set -o errexit
source test/.env
source tool/env/check
source tool/lib/functions.sh
source tool/env/envvars-export

if [[ "$1" == "keep" ]]; then
  shift
else
  source tool/test/setup/create-mysql-user
  source tool/test/setup/check-mysql
  source tool/test/setup/reset-data
fi

export APP_URL=${1:-http://localhost:8073/compiled/source/bibliograph/}
export BROWSER_TYPE=${2:-"firefox"}
node test/playwright/test-login.js
