#!/bin/bash

# checks


# This test runs unit and functional tests that do not need a webserver
CODECEPT_ARGS="--fail-fast"
set -o errexit
source tool/dev/envvars-load
source tool/lib/functions.sh

tool/dev/servers-start

declare -a default=(
  unit
  functional
  "api --env php$PHP_VERSION,setup"
)
declare -a suites=("${@:-${default[@]}}")

log_heading "Running codeception suites '${suites[*]}' "

source tool/dev/check-env
source tool/dev/envvars-check
source tool/dev/create-mysql-user
source tool/dev/check-mysql

for suite in "${suites[@]}"
do
    source tool/test/setup/reset-data
    log_info ">>> Running test suite: $suite ..."
    codecept $CODECEPT_ARGS run $suite -v || exit $?
done

log_info "Tests finished."
exit 0
