#!/bin/bash

# Compiles and starts the testrunner app in the browser
# usage: tool/test/testtapper <application name> <optional: class to be tested>

APP_NAME=${1:-bibliograph-test}
TESTCLASS=$2
if [ "$TESTCLASS" != "" ]; then
  APP_NAME="$APP_NAME?class=$TESTCLASS"
fi

set -o errexit
source test/.env
source tool/env/check
source tool/lib/functions.sh
source tool/env/envvars-export
source tool/test/setup/create-mysql-user
source tool/test/setup/check-mysql
source tool/test/setup/reset-data

export APP_URL
tool/run/app $APP_NAME compile-test.json
