#!/bin/bash

# Compiles and starts the testrunner app in the browser
set -o errexit
source test/.env
source tool/env/check
source tool/lib/functions.sh
source tool/env/envvars-export

tool/env/servers-start
source tool/test/setup/create-mysql-user
source tool/test/setup/check-mysql
source tool/test/setup/reset-data

export BIB_SERVER_URL
tool/run/app bibliograph-test compile-test.json
