#!/bin/bash

# Compiles and starts the testrunner app in the browser
set -o errexit
source tool/env/check
source tool/lib/functions.sh
source test/.env
source tool/env/envvars-check

tool/env/servers-start
source tool/dev/create-mysql-user
source tool/dev/check-mysql
export BIB_SERVER_URL

source tool/test/setup/reset-data
tool/run/app bibliograph-test compile-test.json
