/**
 * Generated by QxTransformer v.0.4. Author Christian Boulanger
 */

/*------------------------------------------------------------------------------

 ------------------------------------------------------------------------------*/
qx.Class.define("bibliograph.plugin.z3950.ImportWindowUi",
{
  extend : bibliograph.plugin.z3950.ImportWindow,
  construct : function()
  {
    this.base(arguments);
    this.__qxtCreateUI();
  },
  members : {
    __qxtCreateUI : function()
    {
      // connecting autogenerated id with 'this'
      var importWindow = this;
      importWindow.setWidth(700);
      importWindow.setCaption(this.tr('Import from library catalogue'));
      importWindow.setShowMinimize(false);
      importWindow.setVisibility("excluded");
      importWindow.setHeight(500);
      qx.event.message.Bus.getInstance().subscribe("logout", function(e) {
        importWindow.close()
      }, this)
      importWindow.addListener("appear", function(e) {
        importWindow.center();
      }, this);
      var qxVbox1 = new qx.ui.layout.VBox(5, null, null);
      qxVbox1.setSpacing(5);
      importWindow.setLayout(qxVbox1);
      var qxToolBar1 = new qx.ui.toolbar.ToolBar();
      importWindow.add(qxToolBar1);
      var datasourceSelectBox = new qx.ui.form.SelectBox();
      this.datasourceSelectBox = datasourceSelectBox;
      datasourceSelectBox.setWidth(150);
      datasourceSelectBox.setMaxHeight(25);
      qxToolBar1.add(datasourceSelectBox);
      var qxListItem1 = new qx.ui.form.ListItem(this.tr('GBV Katalog'), null, null);
      qxListItem1.setLabel(this.tr('GBV Katalog'));
      datasourceSelectBox.add(qxListItem1);
      qxToolBar1.addSpacer();
      var qxHbox1 = new qx.ui.layout.HBox(null, null, null);
      var qxComposite1 = new qx.ui.container.Composite();
      qxComposite1.setLayout(qxHbox1)
      qxComposite1.setPadding(4);
      qxToolBar1.add(qxComposite1, {
        flex : 1
      });
      var searchBox = new qx.ui.form.TextField(null);
      this.searchBox = searchBox;
      searchBox.setPadding(2);
      searchBox.setPlaceholder(this.tr('Enter search term'));
      searchBox.setHeight(26);
      qxComposite1.add(searchBox, {
        flex : 1
      });
      searchBox.addListener("keypress", this._on_keypress, this);
      searchBox.addListener("dblclick", function(e) {
        e.stopPropagation();
      }, this);
      var listView = new bibliograph.ui.reference.ListView();
      this.listView = listView;
      listView.setDatasource("z3950_gbv");
      listView.setDecorator("main");
      listView.setModelType("record");
      listView.setServiceName("bibliograph.plugin.z3950.Service");
      importWindow.add(listView, {
        flex : 1
      });
      var qxHbox2 = new qx.ui.layout.HBox(5, null, null);
      var qxComposite2 = new qx.ui.container.Composite();
      qxComposite2.setLayout(qxHbox2)
      importWindow.add(qxComposite2);
      qxHbox2.setSpacing(5);
      var statusTextLabel = new qx.ui.basic.Label(null);
      qxComposite2.add(statusTextLabel);
      this.listView.bind("store.model.statusText", statusTextLabel, "value", {

      });
      var qxSpacer2 = new qx.ui.core.Spacer(null, null);
      qxComposite2.add(qxSpacer2, {
        flex : 10
      });
      var importButton = new qx.ui.form.Button(this.tr('Import selected records'), null, null);
      this.importButton = importButton;
      importButton.setEnabled(false);
      importButton.setLabel(this.tr('Import selected records'));
      qxComposite2.add(importButton);
      importButton.addListener("execute", function(e) {
        this.importSelected()
      }, this);
      var qxButton1 = new qx.ui.form.Button(this.tr('Close'), null, null);
      qxButton1.setLabel(this.tr('Close'));
      qxComposite2.add(qxButton1);
      qxButton1.addListener("execute", function(e) {
        this.close()
      }, this);
    }
  }
});
