#!/usr/bin/env bash
DEPLOY_TARGET=$1
TARGET_DIR=${2:-/var/www/bibliograph}
TARGET_CONFIG_DIR=${3:-$TARGET_DIR/config}

DIST_DIR=$(pwd)/dist

if [[ "$DEPLOY_TARGET" == "" ]]; then
    echo "Usage:"
    echo "deploy.sh <server> <path> <config directory>"
    echo "   - name of the deployment server as configured in .ssh/config"
    echo "   - target path on that server (optional, default: /var/www/bibliograph)"
    echo "   - path to the directory where config files should be stored (optional)"
    exit 0
fi

echo
echo "This will deploy the code in 'dist' to the following target:"
echo "   Server:           $DEPLOY_TARGET"
echo "   Path:             $TARGET_DIR"
echo "   Config directory: $TARGET_CONFIG_DIR"
read -r -p "Proceed? [y/N] " response
case "$response" in
  [yY][eE][sS]|[yY])
      # pass
      ;;
  *)
      echo "Aborted."
      exit 0;
      ;;
esac

echo " >>> Syncing files..."
ssh $DEPLOY_TARGET "mkdir -p $TARGET_DIR"
shopt -s dotglob
rsync -azpr $DIST_DIR/* $DEPLOY_TARGET:$TARGET_DIR
if [ "$TARGET_CONFIG_DIR" != "$TARGET_DIR/config" ]; then
  ssh $DEPLOY_TARGET "mv $TARGET_DIR/config $TARGET_CONFIG_DIR"
  ssh $DEPLOY_TARGET "sed -i 's/__DIR__ \\. \\\"\\/config\\\"/$TARGET_CONFIG_DIR/' $TARGET_DIR/server.php"
fi
ssh $DEPLOY_TARGET "chmod -R 0777 $TARGET_DIR/server/runtime"
echo "Done."
