#!/bin/bash

# from https://stackoverflow.com/a/13034313

if [ $# -ne 2 ] ; then
  echo "Usage: ssh-add-pass keyfile passphrase"
  exit 1
fi

eval $(ssh-agent)

expect << EOF
  spawn ssh-add $1
  expect "Enter passphrase"
  send "$2\r"
  expect eof
EOF
