<?php

return [
  [
    'id' => 1,
    'type' => 0,
    'default' => 'chicago-author-date',
    'customize' => 1,
    'final' => 0,
    'namedId' => 'csl.style.default',
  ],
  [
    'id' => 2,
    'type' => 0,
    'default' => 'en',
    'customize' => 1,
    'final' => 0,
    'namedId' => 'application.locale',
  ],
  [
    'id' => 3,
    'type' => 0,
    'default' => 'Bibliograph Online Bibliographic Data Manager',
    'customize' => 0,
    'final' => 0,
    'namedId' => 'application.title',
  ],
  [
    'id' => 4,
    'type' => 0,
    'default' => 'bibliograph/icon/bibliograph-logo.png',
    'customize' => 0,
    'final' => 0,
    'namedId' => 'application.logo',
  ],
  [
    'id' => 5,
    'type' => 0,
    'default' => 'normal',
    'customize' => 0,
    'final' => 0,
    'namedId' => 'bibliograph.access.mode',
  ],
  [
    'id' => 6,
    'type' => 3,
    'default' => 'manager,user',
    'customize' => 0,
    'final' => 0,
    'namedId' => 'app.access.userdatabase.roles',
  ],
  [
    'id' => 7,
    'type' => 1,
    'default' => 50,
    'customize' => 0,
    'final' => 0,
    'namedId' => 'bibliograph.duplicates.threshold',
  ],
  [
    'id' => 8,
    'type' => 1,
    'default' => 500,
    'customize' => 0,
    'final' => 0,
    'namedId' => 'plugin.csl.bibliography.maxfolderrecords',
  ],
  [
    'id' => 9,
    'type' => 2,
    'default' => 'false',
    'customize' => 0,
    'final' => 0,
    'namedId' => 'access.enforce_https_login',
  ],
  [
    'id' => 10,
    'type' => 0,
    'default' => 'plaintext',
    'customize' => 0,
    'final' => 0,
    'namedId' => 'authentication.method',
  ],
  [
    'id' => 11,
    'type' => 0,
    'default' => \app\models\BibliographicDatasource::class,
    'customize' => 0,
    'final' => 0,
    'namedId' => 'app.datasource.baseclass',
  ],
  [
    'id' => 12,
    'type' => 0,
    'default' => "bibliograph_datasource",
    'customize' => 0,
    'final' => 0,
    'namedId' => 'app.datasource.baseschema',
  ],
];